name: "aqz/tamaina's Web site"
short_name: "a9z.dev"
description: "aqz/tamainaのWebサイトです。なお、このサイトを生成している「maqz」は簡単にモダンなサイトを作成できるサイトビルダーです。"
author: "aqz / tamaina"
url:
# pages以下をどのようなURLで公開するか指定
# `${scheme}://${host}${path}/`    
# デフォルト例: https://a9z.dev/
#           ↓                  # 右コメント例: https://maqz.example.com/maqz/
  path: ""                      # "/maqz"
  host: "a9z.dev"               # "maqz.example.com"    
  scheme: https                 # "https"
language: ja
pages_src:
  path: "./pages/"
  src: "**/*.{html,htm,pug,md}"
page_namingrule: name
theme_color:
  primary: "#ffffff"
  secondary: "#00251b"
# theme_colorはmanifest用なのでスタイルシートのprimaryなどとは別
default:
  template: default
social_media:
# social_mediaは過去の遺物
  twitter:
    stalk: t_ma1n
    share: true
    card: true
  LINE:
    stalk: false
    share: true
  facebook:
    stalk: false
    share: true
  flickr:
    stalk: false
    share: false
  github:
    stalk: tamaina
    share: false
  share_button: true
rss:
  root: "/blog/"      # blogフォルダの記事を配信(pages直下(ルート)は"/")
  template: "blog"    # blogテンプレートを指定している記事を配信
# 並べかえのために各ページのFrontMatterにdate: (JSON日時)を指定する必要があります
# 無効にしたかったらfalseにしてroot:,template:の行頭に#
disqus: tminghio
# 無効にしたかったらfalse
ga: UA-148331052-1
# 無効にしたかったらfalse
gad: ca-pub-1736621122676736
# 無効にしたかったらfalse
sidebar: true
# サイドバーは無効にできる
manifest:
  display: standalone
metaPages: ['404', 'offline']
# システムで利用するページを列挙
sw: "js|css|png|jpeg|jpg|svg|svgz|woff2"
